services:
  nginx:
    image: nginx:alpine
    container_name: webserver_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8033:80"
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - net_yii2_versi_baru
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    image: php:8.3-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net_yii2_versi_baru
  db:
    image: mysql:latest
    container_name: db_data
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: yii2testing
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/my.conf
    networks:
      - net_yii2_versi_baru
  phpmyadmin_db:
    container_name: phpmyadmin_db
    image: phpmyadmin:latest
    restart: unless-stopped
    tty: true
    environment:
      PMA_HOST: db_data
      PMA_USER: root
      PMA_PASSWORD: 12345
    ports:
      - "8034:80"
    depends_on:
      - db
    networks:
      - net_yii2_versi_baru
networks:
  net_yii2_versi_baru:
    driver: bridge
volumes:
  db:
    driver: local
